### ISSUE TITLE
Datepicker for Presale Block - Ticket Form

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/host-client#20]
This is a time estimate. Use the JS date object to estimate which future block number 
-> time in seconds (!) of unix epoch

- [x] add presale checkbox
- [x] if presale is checked, then -> show datepicker
- [x] implement contract invocation with presale

**Important:** A ticket with a presale needs a finalization time and a blocknumber as parameter.
> The blocknumber defines what block *exactly* is used for the random number that is used for the lottery. The finalization time is used for closing the aftermarket.

> The first block with a timestamp higher than the finalization time does not allow any aftermarket invocations.

**Comment by mialbu** [comment]
This was implemented and merged in pr #37. I'll close this.
