### ISSUE TITLE
Create Event with affiliate

### ISSUE THREAD

**Issue by mialbu** [bc-ticketing/host-client#21]
Add the option to add an affiliate when creating an event. This way the frontend provider is paid for each sold ticket.

**Comment by mialbu** [comment]
@simibac Do we have an according method in the event smart contract? Or did we just implement a method with an affiliate for the sale of tickets?

**Comment by simibac** [comment]
Not yet implemented

**Comment by simibac** [comment]
No need to implement this in the host backend.

**Comment by simibac** [comment]
Only affects the mintTicket functions

**Comment by mialbu** [comment]
Okay, so everything concerning affiliates is handled through the guest-client and I can delete this issue then, @simibac?

**Comment by simibac** [comment]
Yes
