### ISSUE TITLE
Social Trust Certificate Integration

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/host-client#35]
Connect to social certificate api and display whether the meta tag was set correctly. See https://github.com/bc-ticketing/social-trust-certificates-api for more details.

**Comment by simibac** [comment]
When event host past the url of the event website or his twitter profile, the form should show a green checkmark if the correct ETH address was returned from the trust-certificates-api. This can be done when leaving the formfield on as shown here: https://www.w3schools.com/jsref/event_onfocusout.asp

**Comment by mialbu** [comment]
This is already included. Check with an owned website, whether it works correctly, then it can be closed.
